name: "Let's Get Started"
favicon: null
layout_spectrum: 0.8759255374316126
typography_spectrum: 0.1461383542045951
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.77354298485443
  lightness: 0.15069088921882212
  saturation: 0.7647366288583726
  rhythmicContrast: 0.3161824110429734
purpose: []
