name: "Let's Get Started"
favicon: null
layout_spectrum: 0.47015
typography_spectrum: 0.77829
title: "Let's Get Started"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7e8ea'
    - '#a6a8a3'
    - '#050100'
    - '#516472'
    - '#8f322d'
  brandStrength: 0.1875
  lightness: 0.15069088921882212
  saturation: 0.7647366288583726
  rhythmicContrast: 0.3161824110429734
purpose: []
